- name: Create Azure VMs
  hosts: localhost
  connection: local
  vars:
    rg: confluent-kafka
    vnet: kafka-vnet
    storage: wellspringkafka
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ rg }}"
      name: "{{ vnet }}"
      address_prefixes: "10.100.0.0/16"
  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: "{{ rg }}"
      account_type: Premium_LRS
      name: "{{ storage }}"
      kind: StorageV2
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ rg }}"
      name: vms
      address_prefix: "10.100.1.0/24"
      virtual_network: "{{ vnet }}"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ rg }}"
      allocation_method: Static
      domain_name: "{{'project-vm-%02d' | format(item|int)}}"
      name: "{{'pub-ip-%02d' | format(item|int)}}"
    with_sequence: count=12
    register: output_ip_address  
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ rg }}"
      name: "{{'nsg-%02d' | format(item|int)}}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: Broker
          protocol: Tcp
          destination_port_range: 9091
          access: Allow
          priority: 1002
          direction: Inbound
        - name: Broker2
          protocol: Tcp
          destination_port_range: 9092
          access: Allow
          priority: 1003
          direction: Inbound
        - name: HTTP_Connect
          protocol: Tcp
          destination_port_range: 8083
          access: Allow
          priority: 1004
          direction: Inbound
        - name: HTTP_Schema_Share
          protocol: Tcp
          destination_port_range: 8081
          access: Allow
          priority: 1005
          direction: Inbound
        - name: HTTP_Control_Center
          protocol: Tcp
          destination_port_range: 9021
          access: Allow
          priority: 1006
          direction: Inbound
        - name: KSQL
          protocol: Tcp
          destination_port_range: 8088
          access: Allow
          priority: 1007
          direction: Inbound
        - name: Zookeeper1
          protocol: Tcp
          destination_port_range: 2888
          access: Allow
          priority: 1008
          direction: Inbound
        - name: Zookeeper2
          protocol: Tcp
          destination_port_range: 3888
          access: Allow
          priority: 1009
          direction: Inbound
        - name: Zookeeper3
          protocol: Tcp
          destination_port_range: 2181
          access: Allow
          priority: 1010
          direction: Inbound        
        - name: Broker_out
          protocol: Tcp
          destination_port_range: 9091
          access: Allow
          priority: 1002
          direction: Outbound
        - name: Broker2_out
          protocol: Tcp
          destination_port_range: 9092
          access: Allow
          priority: 1003
          direction: Outbound
        - name: HTTP_Connect_out
          protocol: Tcp
          destination_port_range: 8083
          access: Allow
          priority: 1004
          direction: Outbound
        - name: HTTP_Schema_Share_out
          protocol: Tcp
          destination_port_range: 8081
          access: Allow
          priority: 1005
          direction: Outbound
        - name: HTTP_Control_Center_out
          protocol: Tcp
          destination_port_range: 9021
          access: Allow
          priority: 1006
          direction: Outbound
        - name: KSQL_out
          protocol: Tcp
          destination_port_range: 8088
          access: Allow
          priority: 1007
          direction: Outbound
        - name: Zookeeper1_out
          protocol: Tcp
          destination_port_range: 2888
          access: Allow
          priority: 1008
          direction: Outbound
        - name: Zookeeper2_out
          protocol: Tcp
          destination_port_range: 3888
          access: Allow
          priority: 1009
          direction: Outbound
        - name: Zookeeper3_out
          protocol: Tcp
          destination_port_range: 2181
          access: Allow
          priority: 1010
          direction: Outbound
    with_sequence: count=12
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ rg }}"
      name: "{{'nic-%02d' | format(item|int)}}"
      virtual_network: "{{ vnet }}"
      subnet: vms
      public_ip_name: "{{'pub-ip-%02d' | format(item|int)}}"
      security_group: "{{'nsg-%02d' | format(item|int)}}"
    with_sequence: count=12
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ rg }}"
      name: "{{'vm-%02d' | format(item|int)}}"
      vm_size: Standard_F16s_v2
      admin_username: kafka
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/kafka/.ssh/authorized_keys
          key_data: <KEY DATA> kafka@azure-server
      network_interfaces: "{{'nic-%02d' | format(item|int)}}"
      managed_disk_type: Premium_LRS
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
    with_sequence: count=12
  - name: Create Managed Disks
    azure_rm_manageddisk:
      resource_group: "{{ rg }}"
      name: "{{'data-disk-%02d' | format(item|int)}}"
      storage_account_type: Premium_LRS
      managed_by: "{{'vm-%02d' | format(item|int)}}"
      disk_size_gb: 512
    with_sequence: count=12
