rg: confluent-kafka
vnet: kafka-vnet
storage: kafkastorage
rsa_public: <YOUR RSA PUBLIC TOKEN>
project: yourkafkaproject
all:
  childern:
    servers:
      hosts:
        yourkafkaproject-vm-[01:12].eastus.cloudapp.azure.com
          ansible_connection: ssh
          ansible_user: kafka
