---
all:
  vars:
    region: eastus
    rg: kafka-test
    project: kafkatest
    vnet: kafka-test-vnet
    vnet_address: 10.100.0.0/16
    subnet_address: 10.100.1.0/24
    storage: kafkateststorage2
    vm_size: Standard_D2s_v3

zookeeper:
  hosts:
    vm-01:
    vm-02:      
    vm-03:
      
kafka_broker:
  hosts:
    vm-04:      
    vm-05:      
    vm-06:      

schema_registry:
  hosts:
    vm-07:      

kafka_rest:
  hosts:
    vm-08:      

ksql:
  hosts:
    vm-09:      

kafka_connect:
  hosts:
    vm-10:      

control_center:
  hosts:
    vm-11:      
