rg: confluent-kafka
vnet: kafka-vnet
storage: kafkastorage
rsa_public: <YOUR RSA PUBLIC TOKEN>
project: yourkafkaproject
all:
  childern:
    servers:
      hosts:
        vm-[01:12]
          ansible_connection: ssh
          ansible_user: kafka
