- name: Configure Common environment
  include_tasks: common.yml

- name: Build Infrastructure
  include_tasks: vm.yml
  vars:
    vm_names: "{{groups['zookeeper'] + groups['kafka_broker'] + groups['schema_registry'] + groups['kafka_rest'] + groups['ksql'] + groups['kafka_connect'] + groups['control_center'] | unique}}"